<?php
declare(strict_types=1);

namespace App\Services;

/**
 * Secure attachment handling:
 *  - type decided by file content (finfo), never by the browser or extension
 *  - images re-encoded with GD, which strips EXIF/GPS metadata and anything
 *    smuggled after the image data
 *  - PDFs must start with the %PDF- signature
 *  - stored outside the web root under a random name; served only through
 *    AttachmentController after a permission check
 */
final class Uploads
{
    public const ALLOWED = [
        'image/jpeg'      => 'jpg',
        'image/png'       => 'png',
        'image/webp'      => 'webp',
        'application/pdf' => 'pdf',
    ];
    public const MAX_FILES = 3;
    private const MAX_PIXELS = 40_000_000; // refuse decompression bombs

    public static function maxBytes(): int
    {
        return config('uploads.max_mb') * 1024 * 1024;
    }

    public static function acceptAttribute(): string
    {
        return 'image/jpeg,image/png,image/webp,application/pdf,.jpg,.jpeg,.png,.webp,.pdf';
    }

    /**
     * Normalise $_FILES[$field] (single or multiple) into a list of uploaded files.
     * @return array<int, array{name: string, tmp_name: string, error: int, size: int}>
     */
    public static function fromRequest(string $field): array
    {
        $f = $_FILES[$field] ?? null;
        if (!$f) {
            return [];
        }
        $files = [];
        if (is_array($f['name'])) {
            foreach ($f['name'] as $i => $name) {
                $files[] = ['name' => $name, 'tmp_name' => $f['tmp_name'][$i], 'error' => $f['error'][$i], 'size' => $f['size'][$i]];
            }
        } else {
            $files[] = $f;
        }
        return array_values(array_filter($files, static fn ($x) => $x['error'] !== UPLOAD_ERR_NO_FILE));
    }

    /** @return string|null error message, or null when the file is acceptable */
    public static function validate(array $file): ?string
    {
        $name = self::cleanName($file['name']);
        if ($file['error'] === UPLOAD_ERR_INI_SIZE || $file['error'] === UPLOAD_ERR_FORM_SIZE
            || $file['size'] > self::maxBytes()) {
            return "\"{$name}\" is too large. The limit is " . config('uploads.max_mb') . ' MB per file.';
        }
        if ($file['error'] !== UPLOAD_ERR_OK || !is_uploaded_file($file['tmp_name'])) {
            return "\"{$name}\" did not upload completely. Please try again.";
        }
        $mime = (new \finfo(FILEINFO_MIME_TYPE))->file($file['tmp_name']);
        if (!isset(self::ALLOWED[$mime])) {
            return "\"{$name}\" is not a supported file. Please attach a photo (JPG, PNG, WebP) or a PDF.";
        }
        if ($mime === 'application/pdf') {
            $head = (string) file_get_contents($file['tmp_name'], false, null, 0, 5);
            if ($head !== '%PDF-') {
                return "\"{$name}\" does not look like a valid PDF.";
            }
        } else {
            $info = @getimagesize($file['tmp_name']);
            if ($info === false || $info[0] * $info[1] > self::MAX_PIXELS) {
                return "\"{$name}\" could not be read as an image.";
            }
        }
        return null;
    }

    /**
     * Store a validated upload. Returns metadata for ticket_attachments.
     * @return array{original_name: string, stored_name: string, mime_type: string, size_bytes: int, sha256: string}
     */
    public static function store(array $file): array
    {
        $mime = (new \finfo(FILEINFO_MIME_TYPE))->file($file['tmp_name']);
        $ext = self::ALLOWED[$mime];
        $relative = date('Y/m') . '/' . bin2hex(random_bytes(16)) . '.' . $ext;
        $target = config('uploads.path') . '/' . $relative;

        if (!is_dir(dirname($target)) && !mkdir(dirname($target), 0750, true) && !is_dir(dirname($target))) {
            throw new \RuntimeException('Cannot create upload directory');
        }

        if ($mime === 'application/pdf') {
            if (!move_uploaded_file($file['tmp_name'], $target)) {
                throw new \RuntimeException('Cannot store upload');
            }
        } else {
            self::reencode($file['tmp_name'], $target, $mime);
        }
        @chmod($target, 0640);

        return [
            'original_name' => self::cleanName($file['name']),
            'stored_name'   => $relative,
            'mime_type'     => $mime,
            'size_bytes'    => (int) filesize($target),
            'sha256'        => hash_file('sha256', $target),
        ];
    }

    public static function path(string $storedName): string
    {
        // stored_name is generated by us (YYYY/MM/hex.ext); still refuse anything else.
        if (!preg_match('#^\d{4}/\d{2}/[a-f0-9]{32}\.(jpg|png|webp|pdf)$#', $storedName)) {
            throw new \RuntimeException('Invalid stored attachment name');
        }
        return config('uploads.path') . '/' . $storedName;
    }

    private static function reencode(string $source, string $target, string $mime): void
    {
        $img = match ($mime) {
            'image/jpeg' => @imagecreatefromjpeg($source),
            'image/png'  => @imagecreatefrompng($source),
            'image/webp' => @imagecreatefromwebp($source),
        };
        if (!$img) {
            throw new \RuntimeException('Image decode failed');
        }
        if ($mime === 'image/jpeg' && function_exists('exif_read_data')) {
            $img = self::applyOrientation($img, $source);
        }
        $ok = match ($mime) {
            'image/jpeg' => imagejpeg($img, $target, 85),
            'image/png'  => (imagesavealpha($img, true) && imagepng($img, $target, 6)),
            'image/webp' => imagewebp($img, $target, 85),
        };
        imagedestroy($img);
        if (!$ok) {
            throw new \RuntimeException('Image encode failed');
        }
    }

    /** Phone photos store rotation in EXIF, which re-encoding drops: bake it in. */
    private static function applyOrientation(\GdImage $img, string $source): \GdImage
    {
        $exif = @exif_read_data($source);
        $angle = match ((int) ($exif['Orientation'] ?? 1)) {
            3 => 180, 6 => -90, 8 => 90, default => 0,
        };
        if ($angle === 0) {
            return $img;
        }
        $rotated = imagerotate($img, $angle, 0);
        return $rotated ?: $img;
    }

    public static function cleanName(string $name): string
    {
        $name = basename(str_replace('\\', '/', $name));
        $name = preg_replace('/[^\p{L}\p{N} ._()-]+/u', '_', $name) ?? 'file';
        return mb_substr(trim($name) ?: 'file', 0, 200);
    }

    public static function humanSize(int $bytes): string
    {
        return $bytes >= 1048576 ? round($bytes / 1048576, 1) . ' MB' : max(1, (int) round($bytes / 1024)) . ' KB';
    }
}
