-- =============================================================================
-- GENERATED by tools/generate-change-triggers.php on 2026-10-03 20:43 — do not edit by hand.
-- Captures every INSERT / UPDATE / DELETE on business tables into db_change_logs.
-- Who/where comes from session variables the app sets per connection
-- (@app_user_id, @app_ip, @app_ua). Changes made outside the app (phpMyAdmin,
-- mysql CLI) have no @app_ip, so they are recorded as "db:<account>".
-- =============================================================================

DROP TRIGGER IF EXISTS trg_users_ai;
DROP TRIGGER IF EXISTS trg_users_au;
DROP TRIGGER IF EXISTS trg_users_ad;
DELIMITER $$
CREATE TRIGGER trg_users_ai AFTER INSERT ON `users` FOR EACH ROW
BEGIN
    INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('users', CAST(NEW.`id` AS CHAR), 'INSERT', NULL, JSON_OBJECT('id', NEW.`id`, 'role_id', NEW.`role_id`, 'department_id', NEW.`department_id`, 'full_name', NEW.`full_name`, 'email', NEW.`email`, 'phone', NEW.`phone`, 'job_title', NEW.`job_title`, 'password_hash', '[redacted]', 'must_change_password', NEW.`must_change_password`, 'is_active', NEW.`is_active`, 'locked_until', NEW.`locked_until`, 'last_login_at', NEW.`last_login_at`, 'password_changed_at', NEW.`password_changed_at`, 'created_at', NEW.`created_at`, 'updated_at', NEW.`updated_at`), @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
END$$
CREATE TRIGGER trg_users_au AFTER UPDATE ON `users` FOR EACH ROW
BEGIN
    IF JSON_OBJECT('id', OLD.`id`, 'role_id', OLD.`role_id`, 'department_id', OLD.`department_id`, 'full_name', OLD.`full_name`, 'email', OLD.`email`, 'phone', OLD.`phone`, 'job_title', OLD.`job_title`, 'password_hash', '[redacted]', 'must_change_password', OLD.`must_change_password`, 'is_active', OLD.`is_active`, 'locked_until', OLD.`locked_until`, 'last_login_at', OLD.`last_login_at`, 'password_changed_at', OLD.`password_changed_at`, 'created_at', OLD.`created_at`, 'updated_at', OLD.`updated_at`) <> JSON_OBJECT('id', NEW.`id`, 'role_id', NEW.`role_id`, 'department_id', NEW.`department_id`, 'full_name', NEW.`full_name`, 'email', NEW.`email`, 'phone', NEW.`phone`, 'job_title', NEW.`job_title`, 'password_hash', IF(OLD.`password_hash` <=> NEW.`password_hash`, '[redacted]', '[redacted: changed]'), 'must_change_password', NEW.`must_change_password`, 'is_active', NEW.`is_active`, 'locked_until', NEW.`locked_until`, 'last_login_at', NEW.`last_login_at`, 'password_changed_at', NEW.`password_changed_at`, 'created_at', NEW.`created_at`, 'updated_at', NEW.`updated_at`) THEN
        INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('users', CAST(NEW.`id` AS CHAR), 'UPDATE', JSON_OBJECT('id', OLD.`id`, 'role_id', OLD.`role_id`, 'department_id', OLD.`department_id`, 'full_name', OLD.`full_name`, 'email', OLD.`email`, 'phone', OLD.`phone`, 'job_title', OLD.`job_title`, 'password_hash', '[redacted]', 'must_change_password', OLD.`must_change_password`, 'is_active', OLD.`is_active`, 'locked_until', OLD.`locked_until`, 'last_login_at', OLD.`last_login_at`, 'password_changed_at', OLD.`password_changed_at`, 'created_at', OLD.`created_at`, 'updated_at', OLD.`updated_at`), JSON_OBJECT('id', NEW.`id`, 'role_id', NEW.`role_id`, 'department_id', NEW.`department_id`, 'full_name', NEW.`full_name`, 'email', NEW.`email`, 'phone', NEW.`phone`, 'job_title', NEW.`job_title`, 'password_hash', IF(OLD.`password_hash` <=> NEW.`password_hash`, '[redacted]', '[redacted: changed]'), 'must_change_password', NEW.`must_change_password`, 'is_active', NEW.`is_active`, 'locked_until', NEW.`locked_until`, 'last_login_at', NEW.`last_login_at`, 'password_changed_at', NEW.`password_changed_at`, 'created_at', NEW.`created_at`, 'updated_at', NEW.`updated_at`), @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
    END IF;
END$$
CREATE TRIGGER trg_users_ad AFTER DELETE ON `users` FOR EACH ROW
BEGIN
    INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('users', CAST(OLD.`id` AS CHAR), 'DELETE', JSON_OBJECT('id', OLD.`id`, 'role_id', OLD.`role_id`, 'department_id', OLD.`department_id`, 'full_name', OLD.`full_name`, 'email', OLD.`email`, 'phone', OLD.`phone`, 'job_title', OLD.`job_title`, 'password_hash', '[redacted]', 'must_change_password', OLD.`must_change_password`, 'is_active', OLD.`is_active`, 'locked_until', OLD.`locked_until`, 'last_login_at', OLD.`last_login_at`, 'password_changed_at', OLD.`password_changed_at`, 'created_at', OLD.`created_at`, 'updated_at', OLD.`updated_at`), NULL, @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
END$$
DELIMITER ;

DROP TRIGGER IF EXISTS trg_roles_ai;
DROP TRIGGER IF EXISTS trg_roles_au;
DROP TRIGGER IF EXISTS trg_roles_ad;
DELIMITER $$
CREATE TRIGGER trg_roles_ai AFTER INSERT ON `roles` FOR EACH ROW
BEGIN
    INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('roles', CAST(NEW.`id` AS CHAR), 'INSERT', NULL, JSON_OBJECT('id', NEW.`id`, 'slug', NEW.`slug`, 'name', NEW.`name`, 'description', NEW.`description`, 'created_at', NEW.`created_at`), @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
END$$
CREATE TRIGGER trg_roles_au AFTER UPDATE ON `roles` FOR EACH ROW
BEGIN
    IF JSON_OBJECT('id', OLD.`id`, 'slug', OLD.`slug`, 'name', OLD.`name`, 'description', OLD.`description`, 'created_at', OLD.`created_at`) <> JSON_OBJECT('id', NEW.`id`, 'slug', NEW.`slug`, 'name', NEW.`name`, 'description', NEW.`description`, 'created_at', NEW.`created_at`) THEN
        INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('roles', CAST(NEW.`id` AS CHAR), 'UPDATE', JSON_OBJECT('id', OLD.`id`, 'slug', OLD.`slug`, 'name', OLD.`name`, 'description', OLD.`description`, 'created_at', OLD.`created_at`), JSON_OBJECT('id', NEW.`id`, 'slug', NEW.`slug`, 'name', NEW.`name`, 'description', NEW.`description`, 'created_at', NEW.`created_at`), @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
    END IF;
END$$
CREATE TRIGGER trg_roles_ad AFTER DELETE ON `roles` FOR EACH ROW
BEGIN
    INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('roles', CAST(OLD.`id` AS CHAR), 'DELETE', JSON_OBJECT('id', OLD.`id`, 'slug', OLD.`slug`, 'name', OLD.`name`, 'description', OLD.`description`, 'created_at', OLD.`created_at`), NULL, @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
END$$
DELIMITER ;

DROP TRIGGER IF EXISTS trg_permissions_ai;
DROP TRIGGER IF EXISTS trg_permissions_au;
DROP TRIGGER IF EXISTS trg_permissions_ad;
DELIMITER $$
CREATE TRIGGER trg_permissions_ai AFTER INSERT ON `permissions` FOR EACH ROW
BEGIN
    INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('permissions', CAST(NEW.`id` AS CHAR), 'INSERT', NULL, JSON_OBJECT('id', NEW.`id`, 'slug', NEW.`slug`, 'description', NEW.`description`), @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
END$$
CREATE TRIGGER trg_permissions_au AFTER UPDATE ON `permissions` FOR EACH ROW
BEGIN
    IF JSON_OBJECT('id', OLD.`id`, 'slug', OLD.`slug`, 'description', OLD.`description`) <> JSON_OBJECT('id', NEW.`id`, 'slug', NEW.`slug`, 'description', NEW.`description`) THEN
        INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('permissions', CAST(NEW.`id` AS CHAR), 'UPDATE', JSON_OBJECT('id', OLD.`id`, 'slug', OLD.`slug`, 'description', OLD.`description`), JSON_OBJECT('id', NEW.`id`, 'slug', NEW.`slug`, 'description', NEW.`description`), @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
    END IF;
END$$
CREATE TRIGGER trg_permissions_ad AFTER DELETE ON `permissions` FOR EACH ROW
BEGIN
    INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('permissions', CAST(OLD.`id` AS CHAR), 'DELETE', JSON_OBJECT('id', OLD.`id`, 'slug', OLD.`slug`, 'description', OLD.`description`), NULL, @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
END$$
DELIMITER ;

DROP TRIGGER IF EXISTS trg_role_permissions_ai;
DROP TRIGGER IF EXISTS trg_role_permissions_au;
DROP TRIGGER IF EXISTS trg_role_permissions_ad;
DELIMITER $$
CREATE TRIGGER trg_role_permissions_ai AFTER INSERT ON `role_permissions` FOR EACH ROW
BEGIN
    INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('role_permissions', CONCAT_WS(':', NEW.`role_id`, NEW.`permission_id`), 'INSERT', NULL, JSON_OBJECT('role_id', NEW.`role_id`, 'permission_id', NEW.`permission_id`), @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
END$$
CREATE TRIGGER trg_role_permissions_au AFTER UPDATE ON `role_permissions` FOR EACH ROW
BEGIN
    IF JSON_OBJECT('role_id', OLD.`role_id`, 'permission_id', OLD.`permission_id`) <> JSON_OBJECT('role_id', NEW.`role_id`, 'permission_id', NEW.`permission_id`) THEN
        INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('role_permissions', CONCAT_WS(':', NEW.`role_id`, NEW.`permission_id`), 'UPDATE', JSON_OBJECT('role_id', OLD.`role_id`, 'permission_id', OLD.`permission_id`), JSON_OBJECT('role_id', NEW.`role_id`, 'permission_id', NEW.`permission_id`), @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
    END IF;
END$$
CREATE TRIGGER trg_role_permissions_ad AFTER DELETE ON `role_permissions` FOR EACH ROW
BEGIN
    INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('role_permissions', CONCAT_WS(':', OLD.`role_id`, OLD.`permission_id`), 'DELETE', JSON_OBJECT('role_id', OLD.`role_id`, 'permission_id', OLD.`permission_id`), NULL, @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
END$$
DELIMITER ;

DROP TRIGGER IF EXISTS trg_departments_ai;
DROP TRIGGER IF EXISTS trg_departments_au;
DROP TRIGGER IF EXISTS trg_departments_ad;
DELIMITER $$
CREATE TRIGGER trg_departments_ai AFTER INSERT ON `departments` FOR EACH ROW
BEGIN
    INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('departments', CAST(NEW.`id` AS CHAR), 'INSERT', NULL, JSON_OBJECT('id', NEW.`id`, 'name', NEW.`name`, 'code', NEW.`code`, 'is_active', NEW.`is_active`, 'created_at', NEW.`created_at`, 'updated_at', NEW.`updated_at`), @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
END$$
CREATE TRIGGER trg_departments_au AFTER UPDATE ON `departments` FOR EACH ROW
BEGIN
    IF JSON_OBJECT('id', OLD.`id`, 'name', OLD.`name`, 'code', OLD.`code`, 'is_active', OLD.`is_active`, 'created_at', OLD.`created_at`, 'updated_at', OLD.`updated_at`) <> JSON_OBJECT('id', NEW.`id`, 'name', NEW.`name`, 'code', NEW.`code`, 'is_active', NEW.`is_active`, 'created_at', NEW.`created_at`, 'updated_at', NEW.`updated_at`) THEN
        INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('departments', CAST(NEW.`id` AS CHAR), 'UPDATE', JSON_OBJECT('id', OLD.`id`, 'name', OLD.`name`, 'code', OLD.`code`, 'is_active', OLD.`is_active`, 'created_at', OLD.`created_at`, 'updated_at', OLD.`updated_at`), JSON_OBJECT('id', NEW.`id`, 'name', NEW.`name`, 'code', NEW.`code`, 'is_active', NEW.`is_active`, 'created_at', NEW.`created_at`, 'updated_at', NEW.`updated_at`), @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
    END IF;
END$$
CREATE TRIGGER trg_departments_ad AFTER DELETE ON `departments` FOR EACH ROW
BEGIN
    INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('departments', CAST(OLD.`id` AS CHAR), 'DELETE', JSON_OBJECT('id', OLD.`id`, 'name', OLD.`name`, 'code', OLD.`code`, 'is_active', OLD.`is_active`, 'created_at', OLD.`created_at`, 'updated_at', OLD.`updated_at`), NULL, @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
END$$
DELIMITER ;

DROP TRIGGER IF EXISTS trg_categories_ai;
DROP TRIGGER IF EXISTS trg_categories_au;
DROP TRIGGER IF EXISTS trg_categories_ad;
DELIMITER $$
CREATE TRIGGER trg_categories_ai AFTER INSERT ON `categories` FOR EACH ROW
BEGIN
    INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('categories', CAST(NEW.`id` AS CHAR), 'INSERT', NULL, JSON_OBJECT('id', NEW.`id`, 'parent_id', NEW.`parent_id`, 'name', NEW.`name`, 'description', NEW.`description`, 'icon', NEW.`icon`, 'sort_order', NEW.`sort_order`, 'is_active', NEW.`is_active`, 'created_at', NEW.`created_at`, 'updated_at', NEW.`updated_at`), @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
END$$
CREATE TRIGGER trg_categories_au AFTER UPDATE ON `categories` FOR EACH ROW
BEGIN
    IF JSON_OBJECT('id', OLD.`id`, 'parent_id', OLD.`parent_id`, 'name', OLD.`name`, 'description', OLD.`description`, 'icon', OLD.`icon`, 'sort_order', OLD.`sort_order`, 'is_active', OLD.`is_active`, 'created_at', OLD.`created_at`, 'updated_at', OLD.`updated_at`) <> JSON_OBJECT('id', NEW.`id`, 'parent_id', NEW.`parent_id`, 'name', NEW.`name`, 'description', NEW.`description`, 'icon', NEW.`icon`, 'sort_order', NEW.`sort_order`, 'is_active', NEW.`is_active`, 'created_at', NEW.`created_at`, 'updated_at', NEW.`updated_at`) THEN
        INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('categories', CAST(NEW.`id` AS CHAR), 'UPDATE', JSON_OBJECT('id', OLD.`id`, 'parent_id', OLD.`parent_id`, 'name', OLD.`name`, 'description', OLD.`description`, 'icon', OLD.`icon`, 'sort_order', OLD.`sort_order`, 'is_active', OLD.`is_active`, 'created_at', OLD.`created_at`, 'updated_at', OLD.`updated_at`), JSON_OBJECT('id', NEW.`id`, 'parent_id', NEW.`parent_id`, 'name', NEW.`name`, 'description', NEW.`description`, 'icon', NEW.`icon`, 'sort_order', NEW.`sort_order`, 'is_active', NEW.`is_active`, 'created_at', NEW.`created_at`, 'updated_at', NEW.`updated_at`), @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
    END IF;
END$$
CREATE TRIGGER trg_categories_ad AFTER DELETE ON `categories` FOR EACH ROW
BEGIN
    INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('categories', CAST(OLD.`id` AS CHAR), 'DELETE', JSON_OBJECT('id', OLD.`id`, 'parent_id', OLD.`parent_id`, 'name', OLD.`name`, 'description', OLD.`description`, 'icon', OLD.`icon`, 'sort_order', OLD.`sort_order`, 'is_active', OLD.`is_active`, 'created_at', OLD.`created_at`, 'updated_at', OLD.`updated_at`), NULL, @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
END$$
DELIMITER ;

DROP TRIGGER IF EXISTS trg_priorities_ai;
DROP TRIGGER IF EXISTS trg_priorities_au;
DROP TRIGGER IF EXISTS trg_priorities_ad;
DELIMITER $$
CREATE TRIGGER trg_priorities_ai AFTER INSERT ON `priorities` FOR EACH ROW
BEGIN
    INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('priorities', CAST(NEW.`id` AS CHAR), 'INSERT', NULL, JSON_OBJECT('id', NEW.`id`, 'slug', NEW.`slug`, 'name', NEW.`name`, 'description', NEW.`description`, 'tone', NEW.`tone`, 'icon', NEW.`icon`, 'sort_order', NEW.`sort_order`, 'is_default', NEW.`is_default`), @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
END$$
CREATE TRIGGER trg_priorities_au AFTER UPDATE ON `priorities` FOR EACH ROW
BEGIN
    IF JSON_OBJECT('id', OLD.`id`, 'slug', OLD.`slug`, 'name', OLD.`name`, 'description', OLD.`description`, 'tone', OLD.`tone`, 'icon', OLD.`icon`, 'sort_order', OLD.`sort_order`, 'is_default', OLD.`is_default`) <> JSON_OBJECT('id', NEW.`id`, 'slug', NEW.`slug`, 'name', NEW.`name`, 'description', NEW.`description`, 'tone', NEW.`tone`, 'icon', NEW.`icon`, 'sort_order', NEW.`sort_order`, 'is_default', NEW.`is_default`) THEN
        INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('priorities', CAST(NEW.`id` AS CHAR), 'UPDATE', JSON_OBJECT('id', OLD.`id`, 'slug', OLD.`slug`, 'name', OLD.`name`, 'description', OLD.`description`, 'tone', OLD.`tone`, 'icon', OLD.`icon`, 'sort_order', OLD.`sort_order`, 'is_default', OLD.`is_default`), JSON_OBJECT('id', NEW.`id`, 'slug', NEW.`slug`, 'name', NEW.`name`, 'description', NEW.`description`, 'tone', NEW.`tone`, 'icon', NEW.`icon`, 'sort_order', NEW.`sort_order`, 'is_default', NEW.`is_default`), @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
    END IF;
END$$
CREATE TRIGGER trg_priorities_ad AFTER DELETE ON `priorities` FOR EACH ROW
BEGIN
    INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('priorities', CAST(OLD.`id` AS CHAR), 'DELETE', JSON_OBJECT('id', OLD.`id`, 'slug', OLD.`slug`, 'name', OLD.`name`, 'description', OLD.`description`, 'tone', OLD.`tone`, 'icon', OLD.`icon`, 'sort_order', OLD.`sort_order`, 'is_default', OLD.`is_default`), NULL, @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
END$$
DELIMITER ;

DROP TRIGGER IF EXISTS trg_sla_policies_ai;
DROP TRIGGER IF EXISTS trg_sla_policies_au;
DROP TRIGGER IF EXISTS trg_sla_policies_ad;
DELIMITER $$
CREATE TRIGGER trg_sla_policies_ai AFTER INSERT ON `sla_policies` FOR EACH ROW
BEGIN
    INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('sla_policies', CAST(NEW.`id` AS CHAR), 'INSERT', NULL, JSON_OBJECT('id', NEW.`id`, 'priority_id', NEW.`priority_id`, 'response_minutes', NEW.`response_minutes`, 'resolution_minutes', NEW.`resolution_minutes`, 'warn_percent', NEW.`warn_percent`, 'updated_at', NEW.`updated_at`), @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
END$$
CREATE TRIGGER trg_sla_policies_au AFTER UPDATE ON `sla_policies` FOR EACH ROW
BEGIN
    IF JSON_OBJECT('id', OLD.`id`, 'priority_id', OLD.`priority_id`, 'response_minutes', OLD.`response_minutes`, 'resolution_minutes', OLD.`resolution_minutes`, 'warn_percent', OLD.`warn_percent`, 'updated_at', OLD.`updated_at`) <> JSON_OBJECT('id', NEW.`id`, 'priority_id', NEW.`priority_id`, 'response_minutes', NEW.`response_minutes`, 'resolution_minutes', NEW.`resolution_minutes`, 'warn_percent', NEW.`warn_percent`, 'updated_at', NEW.`updated_at`) THEN
        INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('sla_policies', CAST(NEW.`id` AS CHAR), 'UPDATE', JSON_OBJECT('id', OLD.`id`, 'priority_id', OLD.`priority_id`, 'response_minutes', OLD.`response_minutes`, 'resolution_minutes', OLD.`resolution_minutes`, 'warn_percent', OLD.`warn_percent`, 'updated_at', OLD.`updated_at`), JSON_OBJECT('id', NEW.`id`, 'priority_id', NEW.`priority_id`, 'response_minutes', NEW.`response_minutes`, 'resolution_minutes', NEW.`resolution_minutes`, 'warn_percent', NEW.`warn_percent`, 'updated_at', NEW.`updated_at`), @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
    END IF;
END$$
CREATE TRIGGER trg_sla_policies_ad AFTER DELETE ON `sla_policies` FOR EACH ROW
BEGIN
    INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('sla_policies', CAST(OLD.`id` AS CHAR), 'DELETE', JSON_OBJECT('id', OLD.`id`, 'priority_id', OLD.`priority_id`, 'response_minutes', OLD.`response_minutes`, 'resolution_minutes', OLD.`resolution_minutes`, 'warn_percent', OLD.`warn_percent`, 'updated_at', OLD.`updated_at`), NULL, @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
END$$
DELIMITER ;

DROP TRIGGER IF EXISTS trg_settings_ai;
DROP TRIGGER IF EXISTS trg_settings_au;
DROP TRIGGER IF EXISTS trg_settings_ad;
DELIMITER $$
CREATE TRIGGER trg_settings_ai AFTER INSERT ON `settings` FOR EACH ROW
BEGIN
    INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('settings', CAST(NEW.`setting_key` AS CHAR), 'INSERT', NULL, JSON_OBJECT('setting_key', NEW.`setting_key`, 'setting_value', NEW.`setting_value`, 'updated_by', NEW.`updated_by`, 'updated_at', NEW.`updated_at`), @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
END$$
CREATE TRIGGER trg_settings_au AFTER UPDATE ON `settings` FOR EACH ROW
BEGIN
    IF JSON_OBJECT('setting_key', OLD.`setting_key`, 'setting_value', OLD.`setting_value`, 'updated_by', OLD.`updated_by`, 'updated_at', OLD.`updated_at`) <> JSON_OBJECT('setting_key', NEW.`setting_key`, 'setting_value', NEW.`setting_value`, 'updated_by', NEW.`updated_by`, 'updated_at', NEW.`updated_at`) THEN
        INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('settings', CAST(NEW.`setting_key` AS CHAR), 'UPDATE', JSON_OBJECT('setting_key', OLD.`setting_key`, 'setting_value', OLD.`setting_value`, 'updated_by', OLD.`updated_by`, 'updated_at', OLD.`updated_at`), JSON_OBJECT('setting_key', NEW.`setting_key`, 'setting_value', NEW.`setting_value`, 'updated_by', NEW.`updated_by`, 'updated_at', NEW.`updated_at`), @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
    END IF;
END$$
CREATE TRIGGER trg_settings_ad AFTER DELETE ON `settings` FOR EACH ROW
BEGIN
    INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('settings', CAST(OLD.`setting_key` AS CHAR), 'DELETE', JSON_OBJECT('setting_key', OLD.`setting_key`, 'setting_value', OLD.`setting_value`, 'updated_by', OLD.`updated_by`, 'updated_at', OLD.`updated_at`), NULL, @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
END$$
DELIMITER ;

DROP TRIGGER IF EXISTS trg_tickets_ai;
DROP TRIGGER IF EXISTS trg_tickets_au;
DROP TRIGGER IF EXISTS trg_tickets_ad;
DELIMITER $$
CREATE TRIGGER trg_tickets_ai AFTER INSERT ON `tickets` FOR EACH ROW
BEGIN
    INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('tickets', CAST(NEW.`id` AS CHAR), 'INSERT', NULL, JSON_OBJECT('id', NEW.`id`, 'ref', NEW.`ref`, 'title', NEW.`title`, 'description', NEW.`description`, 'category_id', NEW.`category_id`, 'subcategory_id', NEW.`subcategory_id`, 'department_id', NEW.`department_id`, 'location', NEW.`location`, 'priority_id', NEW.`priority_id`, 'status', NEW.`status`, 'requester_id', NEW.`requester_id`, 'assignee_id', NEW.`assignee_id`, 'response_due_at', NEW.`response_due_at`, 'resolve_due_at', NEW.`resolve_due_at`, 'first_response_at', NEW.`first_response_at`, 'resolved_at', NEW.`resolved_at`, 'closed_at', NEW.`closed_at`, 'on_hold_since', NEW.`on_hold_since`, 'hold_minutes', NEW.`hold_minutes`, 'sla_warned_at', NEW.`sla_warned_at`, 'sla_breach_notified_at', NEW.`sla_breach_notified_at`, 'created_at', NEW.`created_at`, 'updated_at', NEW.`updated_at`), @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
END$$
CREATE TRIGGER trg_tickets_au AFTER UPDATE ON `tickets` FOR EACH ROW
BEGIN
    IF JSON_OBJECT('id', OLD.`id`, 'ref', OLD.`ref`, 'title', OLD.`title`, 'description', OLD.`description`, 'category_id', OLD.`category_id`, 'subcategory_id', OLD.`subcategory_id`, 'department_id', OLD.`department_id`, 'location', OLD.`location`, 'priority_id', OLD.`priority_id`, 'status', OLD.`status`, 'requester_id', OLD.`requester_id`, 'assignee_id', OLD.`assignee_id`, 'response_due_at', OLD.`response_due_at`, 'resolve_due_at', OLD.`resolve_due_at`, 'first_response_at', OLD.`first_response_at`, 'resolved_at', OLD.`resolved_at`, 'closed_at', OLD.`closed_at`, 'on_hold_since', OLD.`on_hold_since`, 'hold_minutes', OLD.`hold_minutes`, 'sla_warned_at', OLD.`sla_warned_at`, 'sla_breach_notified_at', OLD.`sla_breach_notified_at`, 'created_at', OLD.`created_at`, 'updated_at', OLD.`updated_at`) <> JSON_OBJECT('id', NEW.`id`, 'ref', NEW.`ref`, 'title', NEW.`title`, 'description', NEW.`description`, 'category_id', NEW.`category_id`, 'subcategory_id', NEW.`subcategory_id`, 'department_id', NEW.`department_id`, 'location', NEW.`location`, 'priority_id', NEW.`priority_id`, 'status', NEW.`status`, 'requester_id', NEW.`requester_id`, 'assignee_id', NEW.`assignee_id`, 'response_due_at', NEW.`response_due_at`, 'resolve_due_at', NEW.`resolve_due_at`, 'first_response_at', NEW.`first_response_at`, 'resolved_at', NEW.`resolved_at`, 'closed_at', NEW.`closed_at`, 'on_hold_since', NEW.`on_hold_since`, 'hold_minutes', NEW.`hold_minutes`, 'sla_warned_at', NEW.`sla_warned_at`, 'sla_breach_notified_at', NEW.`sla_breach_notified_at`, 'created_at', NEW.`created_at`, 'updated_at', NEW.`updated_at`) THEN
        INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('tickets', CAST(NEW.`id` AS CHAR), 'UPDATE', JSON_OBJECT('id', OLD.`id`, 'ref', OLD.`ref`, 'title', OLD.`title`, 'description', OLD.`description`, 'category_id', OLD.`category_id`, 'subcategory_id', OLD.`subcategory_id`, 'department_id', OLD.`department_id`, 'location', OLD.`location`, 'priority_id', OLD.`priority_id`, 'status', OLD.`status`, 'requester_id', OLD.`requester_id`, 'assignee_id', OLD.`assignee_id`, 'response_due_at', OLD.`response_due_at`, 'resolve_due_at', OLD.`resolve_due_at`, 'first_response_at', OLD.`first_response_at`, 'resolved_at', OLD.`resolved_at`, 'closed_at', OLD.`closed_at`, 'on_hold_since', OLD.`on_hold_since`, 'hold_minutes', OLD.`hold_minutes`, 'sla_warned_at', OLD.`sla_warned_at`, 'sla_breach_notified_at', OLD.`sla_breach_notified_at`, 'created_at', OLD.`created_at`, 'updated_at', OLD.`updated_at`), JSON_OBJECT('id', NEW.`id`, 'ref', NEW.`ref`, 'title', NEW.`title`, 'description', NEW.`description`, 'category_id', NEW.`category_id`, 'subcategory_id', NEW.`subcategory_id`, 'department_id', NEW.`department_id`, 'location', NEW.`location`, 'priority_id', NEW.`priority_id`, 'status', NEW.`status`, 'requester_id', NEW.`requester_id`, 'assignee_id', NEW.`assignee_id`, 'response_due_at', NEW.`response_due_at`, 'resolve_due_at', NEW.`resolve_due_at`, 'first_response_at', NEW.`first_response_at`, 'resolved_at', NEW.`resolved_at`, 'closed_at', NEW.`closed_at`, 'on_hold_since', NEW.`on_hold_since`, 'hold_minutes', NEW.`hold_minutes`, 'sla_warned_at', NEW.`sla_warned_at`, 'sla_breach_notified_at', NEW.`sla_breach_notified_at`, 'created_at', NEW.`created_at`, 'updated_at', NEW.`updated_at`), @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
    END IF;
END$$
CREATE TRIGGER trg_tickets_ad AFTER DELETE ON `tickets` FOR EACH ROW
BEGIN
    INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('tickets', CAST(OLD.`id` AS CHAR), 'DELETE', JSON_OBJECT('id', OLD.`id`, 'ref', OLD.`ref`, 'title', OLD.`title`, 'description', OLD.`description`, 'category_id', OLD.`category_id`, 'subcategory_id', OLD.`subcategory_id`, 'department_id', OLD.`department_id`, 'location', OLD.`location`, 'priority_id', OLD.`priority_id`, 'status', OLD.`status`, 'requester_id', OLD.`requester_id`, 'assignee_id', OLD.`assignee_id`, 'response_due_at', OLD.`response_due_at`, 'resolve_due_at', OLD.`resolve_due_at`, 'first_response_at', OLD.`first_response_at`, 'resolved_at', OLD.`resolved_at`, 'closed_at', OLD.`closed_at`, 'on_hold_since', OLD.`on_hold_since`, 'hold_minutes', OLD.`hold_minutes`, 'sla_warned_at', OLD.`sla_warned_at`, 'sla_breach_notified_at', OLD.`sla_breach_notified_at`, 'created_at', OLD.`created_at`, 'updated_at', OLD.`updated_at`), NULL, @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
END$$
DELIMITER ;

DROP TRIGGER IF EXISTS trg_ticket_comments_ai;
DROP TRIGGER IF EXISTS trg_ticket_comments_au;
DROP TRIGGER IF EXISTS trg_ticket_comments_ad;
DELIMITER $$
CREATE TRIGGER trg_ticket_comments_ai AFTER INSERT ON `ticket_comments` FOR EACH ROW
BEGIN
    INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('ticket_comments', CAST(NEW.`id` AS CHAR), 'INSERT', NULL, JSON_OBJECT('id', NEW.`id`, 'ticket_id', NEW.`ticket_id`, 'user_id', NEW.`user_id`, 'body', NEW.`body`, 'is_internal', NEW.`is_internal`, 'created_at', NEW.`created_at`), @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
END$$
CREATE TRIGGER trg_ticket_comments_au AFTER UPDATE ON `ticket_comments` FOR EACH ROW
BEGIN
    IF JSON_OBJECT('id', OLD.`id`, 'ticket_id', OLD.`ticket_id`, 'user_id', OLD.`user_id`, 'body', OLD.`body`, 'is_internal', OLD.`is_internal`, 'created_at', OLD.`created_at`) <> JSON_OBJECT('id', NEW.`id`, 'ticket_id', NEW.`ticket_id`, 'user_id', NEW.`user_id`, 'body', NEW.`body`, 'is_internal', NEW.`is_internal`, 'created_at', NEW.`created_at`) THEN
        INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('ticket_comments', CAST(NEW.`id` AS CHAR), 'UPDATE', JSON_OBJECT('id', OLD.`id`, 'ticket_id', OLD.`ticket_id`, 'user_id', OLD.`user_id`, 'body', OLD.`body`, 'is_internal', OLD.`is_internal`, 'created_at', OLD.`created_at`), JSON_OBJECT('id', NEW.`id`, 'ticket_id', NEW.`ticket_id`, 'user_id', NEW.`user_id`, 'body', NEW.`body`, 'is_internal', NEW.`is_internal`, 'created_at', NEW.`created_at`), @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
    END IF;
END$$
CREATE TRIGGER trg_ticket_comments_ad AFTER DELETE ON `ticket_comments` FOR EACH ROW
BEGIN
    INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('ticket_comments', CAST(OLD.`id` AS CHAR), 'DELETE', JSON_OBJECT('id', OLD.`id`, 'ticket_id', OLD.`ticket_id`, 'user_id', OLD.`user_id`, 'body', OLD.`body`, 'is_internal', OLD.`is_internal`, 'created_at', OLD.`created_at`), NULL, @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
END$$
DELIMITER ;

DROP TRIGGER IF EXISTS trg_ticket_attachments_ai;
DROP TRIGGER IF EXISTS trg_ticket_attachments_au;
DROP TRIGGER IF EXISTS trg_ticket_attachments_ad;
DELIMITER $$
CREATE TRIGGER trg_ticket_attachments_ai AFTER INSERT ON `ticket_attachments` FOR EACH ROW
BEGIN
    INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('ticket_attachments', CAST(NEW.`id` AS CHAR), 'INSERT', NULL, JSON_OBJECT('id', NEW.`id`, 'ticket_id', NEW.`ticket_id`, 'comment_id', NEW.`comment_id`, 'uploaded_by', NEW.`uploaded_by`, 'original_name', NEW.`original_name`, 'stored_name', NEW.`stored_name`, 'mime_type', NEW.`mime_type`, 'size_bytes', NEW.`size_bytes`, 'sha256', NEW.`sha256`, 'is_internal', NEW.`is_internal`, 'created_at', NEW.`created_at`), @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
END$$
CREATE TRIGGER trg_ticket_attachments_au AFTER UPDATE ON `ticket_attachments` FOR EACH ROW
BEGIN
    IF JSON_OBJECT('id', OLD.`id`, 'ticket_id', OLD.`ticket_id`, 'comment_id', OLD.`comment_id`, 'uploaded_by', OLD.`uploaded_by`, 'original_name', OLD.`original_name`, 'stored_name', OLD.`stored_name`, 'mime_type', OLD.`mime_type`, 'size_bytes', OLD.`size_bytes`, 'sha256', OLD.`sha256`, 'is_internal', OLD.`is_internal`, 'created_at', OLD.`created_at`) <> JSON_OBJECT('id', NEW.`id`, 'ticket_id', NEW.`ticket_id`, 'comment_id', NEW.`comment_id`, 'uploaded_by', NEW.`uploaded_by`, 'original_name', NEW.`original_name`, 'stored_name', NEW.`stored_name`, 'mime_type', NEW.`mime_type`, 'size_bytes', NEW.`size_bytes`, 'sha256', NEW.`sha256`, 'is_internal', NEW.`is_internal`, 'created_at', NEW.`created_at`) THEN
        INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('ticket_attachments', CAST(NEW.`id` AS CHAR), 'UPDATE', JSON_OBJECT('id', OLD.`id`, 'ticket_id', OLD.`ticket_id`, 'comment_id', OLD.`comment_id`, 'uploaded_by', OLD.`uploaded_by`, 'original_name', OLD.`original_name`, 'stored_name', OLD.`stored_name`, 'mime_type', OLD.`mime_type`, 'size_bytes', OLD.`size_bytes`, 'sha256', OLD.`sha256`, 'is_internal', OLD.`is_internal`, 'created_at', OLD.`created_at`), JSON_OBJECT('id', NEW.`id`, 'ticket_id', NEW.`ticket_id`, 'comment_id', NEW.`comment_id`, 'uploaded_by', NEW.`uploaded_by`, 'original_name', NEW.`original_name`, 'stored_name', NEW.`stored_name`, 'mime_type', NEW.`mime_type`, 'size_bytes', NEW.`size_bytes`, 'sha256', NEW.`sha256`, 'is_internal', NEW.`is_internal`, 'created_at', NEW.`created_at`), @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
    END IF;
END$$
CREATE TRIGGER trg_ticket_attachments_ad AFTER DELETE ON `ticket_attachments` FOR EACH ROW
BEGIN
    INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('ticket_attachments', CAST(OLD.`id` AS CHAR), 'DELETE', JSON_OBJECT('id', OLD.`id`, 'ticket_id', OLD.`ticket_id`, 'comment_id', OLD.`comment_id`, 'uploaded_by', OLD.`uploaded_by`, 'original_name', OLD.`original_name`, 'stored_name', OLD.`stored_name`, 'mime_type', OLD.`mime_type`, 'size_bytes', OLD.`size_bytes`, 'sha256', OLD.`sha256`, 'is_internal', OLD.`is_internal`, 'created_at', OLD.`created_at`), NULL, @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
END$$
DELIMITER ;

DROP TRIGGER IF EXISTS trg_ticket_status_history_ai;
DROP TRIGGER IF EXISTS trg_ticket_status_history_au;
DROP TRIGGER IF EXISTS trg_ticket_status_history_ad;
DELIMITER $$
CREATE TRIGGER trg_ticket_status_history_ai AFTER INSERT ON `ticket_status_history` FOR EACH ROW
BEGIN
    INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('ticket_status_history', CAST(NEW.`id` AS CHAR), 'INSERT', NULL, JSON_OBJECT('id', NEW.`id`, 'ticket_id', NEW.`ticket_id`, 'from_status', NEW.`from_status`, 'to_status', NEW.`to_status`, 'changed_by', NEW.`changed_by`, 'note', NEW.`note`, 'created_at', NEW.`created_at`), @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
END$$
CREATE TRIGGER trg_ticket_status_history_au AFTER UPDATE ON `ticket_status_history` FOR EACH ROW
BEGIN
    IF JSON_OBJECT('id', OLD.`id`, 'ticket_id', OLD.`ticket_id`, 'from_status', OLD.`from_status`, 'to_status', OLD.`to_status`, 'changed_by', OLD.`changed_by`, 'note', OLD.`note`, 'created_at', OLD.`created_at`) <> JSON_OBJECT('id', NEW.`id`, 'ticket_id', NEW.`ticket_id`, 'from_status', NEW.`from_status`, 'to_status', NEW.`to_status`, 'changed_by', NEW.`changed_by`, 'note', NEW.`note`, 'created_at', NEW.`created_at`) THEN
        INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('ticket_status_history', CAST(NEW.`id` AS CHAR), 'UPDATE', JSON_OBJECT('id', OLD.`id`, 'ticket_id', OLD.`ticket_id`, 'from_status', OLD.`from_status`, 'to_status', OLD.`to_status`, 'changed_by', OLD.`changed_by`, 'note', OLD.`note`, 'created_at', OLD.`created_at`), JSON_OBJECT('id', NEW.`id`, 'ticket_id', NEW.`ticket_id`, 'from_status', NEW.`from_status`, 'to_status', NEW.`to_status`, 'changed_by', NEW.`changed_by`, 'note', NEW.`note`, 'created_at', NEW.`created_at`), @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
    END IF;
END$$
CREATE TRIGGER trg_ticket_status_history_ad AFTER DELETE ON `ticket_status_history` FOR EACH ROW
BEGIN
    INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('ticket_status_history', CAST(OLD.`id` AS CHAR), 'DELETE', JSON_OBJECT('id', OLD.`id`, 'ticket_id', OLD.`ticket_id`, 'from_status', OLD.`from_status`, 'to_status', OLD.`to_status`, 'changed_by', OLD.`changed_by`, 'note', OLD.`note`, 'created_at', OLD.`created_at`), NULL, @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
END$$
DELIMITER ;

DROP TRIGGER IF EXISTS trg_notification_preferences_ai;
DROP TRIGGER IF EXISTS trg_notification_preferences_au;
DROP TRIGGER IF EXISTS trg_notification_preferences_ad;
DELIMITER $$
CREATE TRIGGER trg_notification_preferences_ai AFTER INSERT ON `notification_preferences` FOR EACH ROW
BEGIN
    INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('notification_preferences', CONCAT_WS(':', NEW.`user_id`, NEW.`event`), 'INSERT', NULL, JSON_OBJECT('user_id', NEW.`user_id`, 'event', NEW.`event`, 'in_app', NEW.`in_app`, 'email', NEW.`email`), @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
END$$
CREATE TRIGGER trg_notification_preferences_au AFTER UPDATE ON `notification_preferences` FOR EACH ROW
BEGIN
    IF JSON_OBJECT('user_id', OLD.`user_id`, 'event', OLD.`event`, 'in_app', OLD.`in_app`, 'email', OLD.`email`) <> JSON_OBJECT('user_id', NEW.`user_id`, 'event', NEW.`event`, 'in_app', NEW.`in_app`, 'email', NEW.`email`) THEN
        INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('notification_preferences', CONCAT_WS(':', NEW.`user_id`, NEW.`event`), 'UPDATE', JSON_OBJECT('user_id', OLD.`user_id`, 'event', OLD.`event`, 'in_app', OLD.`in_app`, 'email', OLD.`email`), JSON_OBJECT('user_id', NEW.`user_id`, 'event', NEW.`event`, 'in_app', NEW.`in_app`, 'email', NEW.`email`), @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
    END IF;
END$$
CREATE TRIGGER trg_notification_preferences_ad AFTER DELETE ON `notification_preferences` FOR EACH ROW
BEGIN
    INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)
    VALUES ('notification_preferences', CONCAT_WS(':', OLD.`user_id`, OLD.`event`), 'DELETE', JSON_OBJECT('user_id', OLD.`user_id`, 'event', OLD.`event`, 'in_app', OLD.`in_app`, 'email', OLD.`email`), NULL, @app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER())), NOW(6), '', '');
END$$
DELIMITER ;
