<?php
declare(strict_types=1);

// Generates database/change_triggers.sql from the live schema: one AFTER
// INSERT/UPDATE/DELETE trigger per business table, writing old/new values as
// JSON into db_change_logs (whose own trigger adds it to the hash chain).
//
// Re-run after any schema change:  php tools/generate-change-triggers.php
// Then import the file again (it drops and recreates the triggers).

if (PHP_SAPI !== 'cli') {
    http_response_code(404);
    exit;
}
require dirname(__DIR__) . '/app/bootstrap.php';

use App\Core\DB;

// Business tables to capture => primary-key columns (composite keys joined with ':').
// Not captured, on purpose:
//   audit_logs, db_change_logs, audit_chain_head — the trail itself
//   login_attempts — sign-ins are already in audit_logs; high volume
//   notifications, email_queue — derived messages, high volume; email bodies
//   ticket_sequences — counter only
const TABLES = [
    'users'                    => ['id'],
    'roles'                    => ['id'],
    'permissions'              => ['id'],
    'role_permissions'         => ['role_id', 'permission_id'],
    'departments'              => ['id'],
    'categories'               => ['id'],
    'priorities'               => ['id'],
    'sla_policies'             => ['id'],
    'settings'                 => ['setting_key'],
    'tickets'                  => ['id'],
    'ticket_comments'          => ['id'],
    'ticket_attachments'       => ['id'],
    'ticket_status_history'    => ['id'],
    'notification_preferences' => ['user_id', 'event'],
];

// Secrets are never copied into the trail; only the fact that they changed.
const REDACT = ['users' => ['password_hash']];

$db = config('db.database');
$out = [];
$out[] = '-- =============================================================================';
$out[] = '-- GENERATED by tools/generate-change-triggers.php on ' . date('Y-m-d H:i') . ' — do not edit by hand.';
$out[] = '-- Captures every INSERT / UPDATE / DELETE on business tables into db_change_logs.';
$out[] = '-- Who/where comes from session variables the app sets per connection';
$out[] = '-- (@app_user_id, @app_ip, @app_ua). Changes made outside the app (phpMyAdmin,';
$out[] = '-- mysql CLI) have no @app_ip, so they are recorded as "db:<account>".';
$out[] = '-- =============================================================================';
$out[] = '';

foreach (TABLES as $table => $pk) {
    $cols = DB::run(
        'SELECT COLUMN_NAME FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ? ORDER BY ORDINAL_POSITION',
        [$db, $table]
    )->fetchAll(PDO::FETCH_COLUMN);
    if (!$cols) {
        fwrite(STDERR, "Table {$table} not found\n");
        exit(1);
    }

    $json = static function (string $row, string $op) use ($cols, $table): string {
        $pairs = [];
        foreach ($cols as $c) {
            if (in_array($c, REDACT[$table] ?? [], true)) {
                $value = $op === 'UPDATE' && $row === 'NEW'
                    ? "IF(OLD.`{$c}` <=> NEW.`{$c}`, '[redacted]', '[redacted: changed]')"
                    : "'[redacted]'";
                $pairs[] = "'{$c}', {$value}";
                continue;
            }
            $pairs[] = "'{$c}', {$row}.`{$c}`";
        }
        return 'JSON_OBJECT(' . implode(', ', $pairs) . ')';
    };
    $recordId = static fn (string $row) => count($pk) === 1
        ? "CAST({$row}.`{$pk[0]}` AS CHAR)"
        : 'CONCAT_WS(\':\', ' . implode(', ', array_map(static fn ($k) => "{$row}.`{$k}`", $pk)) . ')';

    $who = "@app_user_id, COALESCE(@app_ip, 'db'), COALESCE(@app_ua, CONCAT('db:', CURRENT_USER()))";
    $insert = static fn (string $op, string $rid, string $old, string $new) =>
        "    INSERT INTO db_change_logs (table_name, record_id, operation, old_values, new_values, user_id, ip_address, user_agent, created_at, prev_hash, row_hash)\n"
        . "    VALUES ('{$table}', {$rid}, '{$op}', {$old}, {$new}, {$who}, NOW(6), '', '');";

    foreach (['ai' => 'INSERT', 'au' => 'UPDATE', 'ad' => 'DELETE'] as $suffix => $op) {
        $out[] = "DROP TRIGGER IF EXISTS trg_{$table}_{$suffix};";
    }
    $out[] = 'DELIMITER $$';

    $out[] = "CREATE TRIGGER trg_{$table}_ai AFTER INSERT ON `{$table}` FOR EACH ROW";
    $out[] = 'BEGIN';
    $out[] = $insert('INSERT', $recordId('NEW'), 'NULL', $json('NEW', 'INSERT'));
    $out[] = 'END$$';

    // UPDATE: skip no-op updates (identical before/after) to keep the trail meaningful.
    $old = $json('OLD', 'UPDATE');
    $new = $json('NEW', 'UPDATE');
    $out[] = "CREATE TRIGGER trg_{$table}_au AFTER UPDATE ON `{$table}` FOR EACH ROW";
    $out[] = 'BEGIN';
    $out[] = "    IF {$old} <> {$new} THEN";
    $out[] = '    ' . $insert('UPDATE', $recordId('NEW'), $old, $new);
    $out[] = '    END IF;';
    $out[] = 'END$$';

    $out[] = "CREATE TRIGGER trg_{$table}_ad AFTER DELETE ON `{$table}` FOR EACH ROW";
    $out[] = 'BEGIN';
    $out[] = $insert('DELETE', $recordId('OLD'), $json('OLD', 'DELETE'), 'NULL');
    $out[] = 'END$$';
    $out[] = 'DELIMITER ;';
    $out[] = '';
}

$file = BASE_PATH . '/database/change_triggers.sql';
file_put_contents($file, implode("\n", $out));
echo 'Wrote ' . count(TABLES) * 3 . " triggers to database/change_triggers.sql\n";
